### ISSUE TITLE
🗺️ Gererate tiles with Zoomify

### ISSUE THREAD

**Issue by bangank36** [bangank36/spriral-learning#11]
## Summary
- Second attempt to create Zoomify tile images from large images using https://github.com/Daniel-KM/LibraryZoomify repo
- First attempt on gitpod.io produce error with files permission

## Tasks

- [x] Find new image on Pexels https://github.com/bangank36/zoomify-generator/pull/1
- [x] Install `php` and `composer` for the lap https://github.com/bangank36/zoomify-generator/pull/2
- [x] Create first index.php file to run against the sample image https://github.com/bangank36/zoomify-generator/pull/2

**Comment by bangank36** [comment]
The kick-off has completed, this issue is created in this repo by mistake, should move next issue into correct repo
